export const GAME_ACTION_TYPES = {
  INIT: "INIT",
  UNDO_LAST_MOVE: "UNDO_LAST_MOVE",
  RESET_DATA: "RESET_DATA",
};

export const PLAYER_ACTION_TYPES = {
  COLLECT_FROM_START: "COLLECT_FROM_START",
  BUY_PROPERTY: "BUY_PROPERTY",
  PAY_RENT: "PAY_RENT",
  MORTGAGE: "MORTGAGE",
  REDEEM: "REDEEM",
  PAY_INCOME_TAX: "PAY_INCOME_TAX",
  PAY_TO: "PAY_TO",
  RECEIVE_FROM: "RECEIVE_FROM",
  GET_OUT_OF_PRISON_OR_PRICE_WAR: "GET_OUT_OF_PRISON_OR_PRICE_WAR",
  ANTI_MONOPOLY_FOUNDATION: "ANTI_MONOPOLY_FOUNDATION",
  PROPERTY_TAX: "PROPERTY_TAX",
  ADD_HOUSE: "ADD_HOUSE",
};
